name: vocal_looper_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  provider: ^6.1.5+1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  record: ^6.1.2
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  path: ^1.9.1
  test: ^1.26.2
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  audio_session: ^0.2.2
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  patrol: ^4.1.0

flutter:
  uses-material-design: true

patrol:
  app_name: My App
  test_directory: integration_test
  android:
    package_name: com.example.vocal_looper_app
