name: Flutter CI

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Installing dependencies
        run: flutter pub get
        working-directory: ./vocal_looper_app

      - name: Analyzing project code
        run: flutter analyze
        working-directory: ./vocal_looper_app

      - name: Running tests
        run: flutter test
        working-directory: ./vocal_looper_app

      - name: Building Android app
        run: flutter build apk --debug
        working-directory: ./vocal_looper_app
